language: c

dist: xenial
services:
  - xvfb
  - docker

env:
  - MINICONDA_DIR=$HOME/miniconda ENVIRONMENT_DIR=$HOME/envs ENVIRONMENT_NAME=test-environment MANTIDIMAGING_DOCKER_RUN="docker run -e DISPLAY -v $HOME/.Xauthority:/home/developer/.Xauthority -v /tmp/.X11-unix:/tmp/.X11-unix:ro -v $TRAVIS_BUILD_DIR:/opt/mantidimaging -t dtasev/mantidimaging:travis-ci-2019.10"

before_install:
  - docker pull dtasev/mantidimaging:travis-ci-2019.10

jobs:
  include:
    - stage: test
      script:
        - $MANTIDIMAGING_DOCKER_RUN flake8
        - $MANTIDIMAGING_DOCKER_RUN mypy --ignore-missing-imports mantidimaging
        - $MANTIDIMAGING_DOCKER_RUN nosetests --xunit-file=/opt/result-report.xml

    - stage: upload-nightly
      if: branch = master AND env(TRAVIS_EVENT_TYPE) = cron
      script:
        - |
          if [[ $UPLOAD_PACKAGE = "true" ]]; then
            conda config --set anaconda_upload yes;
          fi
        - make build-conda-package-nightly
        # stop caching from being ran for a package build
        # this prevent caching big packages like anaconda and conda-forge
        # that are only necessary for building the package
        - exit 0

