language: c

dist: xenial
services:
  - xvfb

env:
  - MINICONDA_DIR=$HOME/miniconda ENVIRONMENT_DIR=$HOME/envs ENVIRONMENT_NAME=test-environment

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $MINICONDA_DIR
  - export PATH="$MINICONDA_DIR/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # set up the conda environment variables in this shell, for conda activate
  - source $MINICONDA_DIR/etc/profile.d/conda.sh
  # build a local package and install
  - conda config --append channels conda-forge
  - make build-conda-deps-package
  - conda create -n $ENVIRONMENT_NAME -c conda-forge --use-local --only-deps mantidimaging
  - conda activate $ENVIRONMENT_NAME

  - pip install -r deps/dev-requirements.pip

jobs:
  include:
    - stage: test
      script:
        - flake8
        - make mypy
        - nosetests --verbose

    - stage: upload-nightly
      if: branch = master AND env(TRAVIS_EVENT_TYPE) = cron
      script:
        - |
          if [[ $UPLOAD_PACKAGE = "true" ]]; then
            conda config --set anaconda_upload yes;
          fi
        - make build-conda-package-nightly
        # stop caching from being ran for a package build
        # this prevent caching big packages like anaconda and conda-forge
        # that are only necessary for building the package
        - exit 0

