language: c

# cache:
#     directories:
#         - $HOME/miniconda/

env:
    - MINICONDA_DIR=$HOME/miniconda
    - ENVIRONMENT_DIR=$HOME/envs
    - ENVIRONMENT_NAME=test-environment

install:
    - |
      if [[ ! -f $MINICONDA_DIR/bin/conda ]]; then
        rm -rf $MINICONDA_DIR;
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        bash miniconda.sh -b -p $MINICONDA_DIR;
      fi
    - export PATH="$MINICONDA_DIR/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a
    # set up the conda environment variables in this shell, for conda activate
    - source $MINICONDA_DIR/etc/profile.d/conda.sh

    - conda config --add channels conda-forge
    - conda config --add channels $UPLOAD_USER
    - |
      if [[ -f $ENVIRONMENT_DIR/$ENVIRONMENT_NAME/bin/mantidimaging ]]; then
        conda activate $ENVIRONMENT_DIR/$ENVIRONMENT_NAME;
        conda remove --force mantidimaging;
        conda install --only-deps mantidimaging;
      else
        conda create --prefix $ENVIRONMENT_DIR/$ENVIRONMENT_NAME --only-deps mantidimaging;
        conda activate $ENVIRONMENT_DIR/$ENVIRONMENT_NAME;
      fi

jobs:
    include:
        - stage: test
          script:
            - pip install -r deps/dev-requirements.pip
            - make test

        - stage: upload-release
          if: env(BUILD_PACKAGE) = "true" AND env(MANTIDIMAGING_BUILD_TYPE) = "release"
          script:
            - |
              if [[ $UPLOAD_PACKAGE = "true" ]]; then
                conda config --set anaconda_upload yes;
              fi
            - make build-conda-package-release

        - stage: upload-nightly
          if: env(BUILD_PACKAGE) = "true" AND env(MANTIDIMAGING_BUILD_TYPE) = "nightly"
          script:
            - |
              if [[ $UPLOAD_PACKAGE = "true" ]]; then
                conda config --set anaconda_upload yes;
              fi
            - make build-conda-package-nightly
