language: c

cache:
    directories:
        - $HOME/miniconda/

install:
    - |
      if [[ ! -f $HOME/miniconda/bin/conda ]]; then
        rm -rf $HOME/miniconda;
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        bash miniconda.sh -b -p $HOME/miniconda;
      fi
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a

    - conda config --add channels conda-forge
    - conda config --add channels dtasev
    - |
      if [[ -f $HOME/miniconda/envs/test-environment/bin/mantidimaging ]]; then
        source activate test-environment;
        conda remove --force mantidimaging;
        conda install mantidimaging;
      else
        conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION mantidimaging;
        source activate test-environment;
      fi

jobs:
    include:
        - stage: test
          script: make test

        - stage: upload-release
          if: env(BUILD_PACKAGE) = "true" AND env(MANTIDIMAGING_BUILD_TYPE) = "release"
          script:
            - |
              if [[ $UPLOAD_PACKAGE = "true" ]]; then
                conda config --set anaconda_upload yes;
              fi
            - make build-conda-package-release

        - stage: upload-nightly
          if: env(BUILD_PACKAGE) = "true" AND env(MANTIDIMAGING_BUILD_TYPE) = "nightly"
          script:
            - |
              if [[ $UPLOAD_PACKAGE = "true" ]]; then
                conda config --set anaconda_upload yes;
              fi
            - make build-conda-package-nightly
