language: python

python:
    - '3.7.3'

cache:
    directories:
        - $HOME/miniconda/

install:
    - if [[ ! -f $HOME/miniconda/bin/conda ]]; then
        rm -rf $HOME/miniconda;
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        bash miniconda.sh -b -p $HOME/miniconda;
      fi
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a

    - conda config --add channels conda-forge
    - conda config --add channels dtasev
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION mantidimaging
    - source activate test-environment

script:
    - make test