name: mantidimaging-py35

channels:
  - conda-forge
  - dgursoy
  - defaults

dependencies:
  - python=3.5
  - tomopy=1.1.2
  - pyfftw
  - astropy
  - pip:
    - IPython
    - nose
    - nose-randomly
    - testfixtures
    - flake8
    - GitPython
    - sphinx
