name: mantidimaging

channels:
  - conda-forge
  - dgursoy
  - defaults

dependencies:
  - python=2.7
  - tomopy=1.1.2
  - pyfftw
  - astropy
  - pip:
    - enum34
    - IPython
    - nose
    - nose-randomly
    - mock
    - testfixtures
    - flake8=3.5.0
    - pylint=1.8.2
    - GitPython
    - sphinx
