name: mantidimaging-py35

channels:
  - conda-forge
  - dgursoy
  - defaults

dependencies:
  - python=3.5
  - tomopy=1.1.2
  - pyfftw
  - astropy
  - pip:
    - IPython
    - nose
    - nose-randomly
    - testfixtures
    - flake8=3.5.0
    - pylint=1.8.2
    - GitPython
    - sphinx
