name: mantidimaging
channels:
  - mantid
  - dtasev
  - astra-toolbox/label/dev
  - conda-forge
  - defaults
dependencies:
  - mantidimaging
  - pip
  - sharedarray
  - sarepy
  - astra-toolbox
  - cudatookit=10.2
  - pip:
      - pytest
      - pytest-cov
      - coveralls
      - pyqt5==5.15
      - pyqtgraph==0.11
      - yapf
      - mypy
      - flake8
      - testfixtures
      - coverage
      - hazelnut
      - gitpython
      - mock
      - pylint
      - sphinx
      - pytest-randomly
      - pytest-parallel
      - psutil
      - isort
      - cupy-cuda102