{% set name = 'mantidimaging' %}

{% set version_tag = environ.get('GIT_DESCRIBE_TAG', '0.0.0') %}
{% set version_number = environ.get('GIT_DESCRIBE_NUMBER', '0') | string %}

{% set version = version_tag + '_' + version_number if version_number != '0' else version_tag %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  path: ../../

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python 3.5
    - pip
    - setuptools
    - sphinx
  run:
    - python 3.5
    - astropy
    - numpy
    - scipy
    - matplotlib >=2.1.0
    - tomopy >=1.1.2
    - pyqt

test:
  imports:
    - mantidimaging

about:
  home: https://github.com/mantidproject/mantidimaging
  license: GPL-3
  license_file: LICENSE.txt
