{% set name = 'mantidimaging' %}

  {% set version_tag = environ.get('GIT_DESCRIBE_TAG', '0.0.0') %}
  {% set version_number = environ.get('GIT_DESCRIBE_NUMBER', '0') | string %}
  {% set version_number = '_' + version_number if version_number != '0' else '' %}

  {% set version = version_tag + version_number %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  path: ../

requirements:
  build:
    - python =3.7.3
    - pip
    - setuptools
    - sphinx
  run:
    - python =3.7.3
    - pip
    - astropy >=3.2.1
    - scipy
    - scikit-image
    - numpy >=1.16
    - matplotlib =2.2.3
    - tomopy =1.7.0
    - requests
    - requests-futures =1.0.0
    - python-socketio =4.3.0
    - h5py
    - pyqt
    - pyqtgraph =0.10

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install --no-deps --ignore-installed .

test:
  imports:
    - mantidimaging

app:
  summary: "Mantid Imaging"
  own_environment: True

about:
  home: https://github.com/mantidproject/mantidimaging
  license: GPL-3
  license_file: LICENSE.txt
