{% set name = "mantidimaging" %}
{% set version = "master" %}
{% set sha256 = "" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  path: ../../../

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python 3.5
    - pip
    - setuptools
    - sphinx
  run:
    - python 3.5
    - astropy
    - numpy
    - scipy
    - matplotlib 2.1.0
    - tomopy 1.1.2
    - pyqt

test:
  imports:
    - mantidimaging

about:
  home: https://github.com/mantidproject/mantidimaging
  license: GPL-3
  license_file: LICENSE.txt
