package:
  name: mantidimaging
  version: "nightly"

source:
  path: ../../../

requirements:
  build:
    - python 3.5
    - setuptools
    - sphinx
  run:
    - python 3.5
    - astropy
    - numpy
    - scipy
    - matplotlib
    - tomopy 1.1.2
    - pyqt

test:
  imports:
    - mantidimaging
  requires:
    - nose
    - coverage
    - flake8

about:
  home: https://github.com/mantidproject/mantidimaging
  license: GPL-3
  license_file: LICENSE.txt

app:
  entry: mantidimaging-gui
  summary: "GUI for Mantid Imaging toolkit"
  icon:
