package:
  name: mantidimaging
  version: "nightly"

source:
  git_rev: master
  git_url: https://github.com/mantidproject/mantidimaging.git

requirements:
  build:
    - python {{ python }}
    - setuptools
    - sphinx
  run:
    - python {{ python }}
    - astropy
    - numpy
    - scipy
    - matplotlib
    - tomopy
    - pyqt

test:
  imports:
    - mantidimaging
  requires:
    - nose
    - coverage
    - flake8

about:
  home: https://github.com/mantidproject/mantidimaging
  license: GPL-3
  license_file: LICENSE.txt

app:
  entry: mantidimaging-gui
  summary: "GUI for Mantid Imaging toolkit"
  icon:
